* renconst.h
* the declarations for renconst.F
* generated by WriteRenConst 24 Jul 2006 0:59

	double complex dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1, dZZA1
	double complex dZZZ1, dZfL1(3,2,2), dZfR1(3,2,2)
	common /uurenconst/ dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1
	common /uurenconst/ dZZA1, dZZZ1, dZfL1, dZfR1

	integer sizeof_rc
	parameter (sizeof_rc = 32)
	double complex rc(sizeof_rc)
	equivalence (dMWsq1, rc)

