* renconst.h
* the declarations for renconst.F
* generated by WriteRenConst 3 Aug 2006 1:51

	double complex dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1, dZZA1
	double complex dZZZ1, dZfL1(4,2,2), dZfR1(4,2,2)
	common /ddrenconst/ dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1
	common /ddrenconst/ dZZA1, dZZZ1, dZfL1, dZfR1

	integer sizeof_rc
	parameter (sizeof_rc = 40)
	double complex rc(sizeof_rc)
	equivalence (dMWsq1, rc)

